[package]
name = "hexstack"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
console = "0.16.0"
dialoguer = "0.12.0"
indicatif = "0.18.0"
ripress = { version = "1.8.4" , features = ["with-wynd"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "fs", "process"] }
wynd = { version = "0.4.3" , features = ["with-ripress"] }
